### ISSUE TITLE
Are you using Eino ?

### ISSUE THREAD

**Issue by hi-pender** [cloudwego/eino#68]
## The purpose of this issue

We are always interested in finding out who is using Eino, what attracted you to using it, how we can listen to your needs and if you are interested, help promote your organization.

- We have people reaching out to us asking, who uses Eino in production?
- We’d like to listen to what you would like to see in Eino and your scenarios?
- We'd like to help promote your organization and work with you

## What we would like from you

Submit a comment in this issue to include the following information
  - Your organization or company
  - Link to your website
  - Your country
  - Your contact info to reach out to you: blog, email or Twitter (at least one).
  - What is your scenario for using Eino?
  - Are you running you application in PoC(proof of concept), testing or production?

```yaml
Organization/Company: ByteDance
Website: https://bytedance.com
Country: China
Contact: conduct@cloudwego.io
Usage scenario: Using Eino to build a meal ordering assistant
Status: Production
```
